-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 13:44:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crud_noticia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_noticia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_noticia` DEFAULT CHARACTER SET utf8 ;
USE `crud_noticia` ;

-- -----------------------------------------------------
-- Table `crud_noticia`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_noticia`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_noticia`),
  UNIQUE INDEX `noticiacol_UNIQUE` (`titulo` ASC) ,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) ,
  UNIQUE INDEX `id_noticia_UNIQUE` (`id_noticia` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_noticia`.`palavra_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_noticia`.`palavra_chave` (
  `id_palavra_chave` INT NOT NULL AUTO_INCREMENT,
  `palavra` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_palavra_chave`),
  UNIQUE INDEX `palavra_UNIQUE` (`palavra` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_noticia`.`noticia_has_palavra_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_noticia`.`noticia_has_palavra_chave` (
  `noticia_id` INT NOT NULL,
  `palavra_chave_id` INT NOT NULL,
  PRIMARY KEY (`noticia_id`, `palavra_chave_id`),
  INDEX `fk_noticia_has_palavra_chave_palavra_chave1_idx` (`palavra_chave_id` ASC) ,
  INDEX `fk_noticia_has_palavra_chave_noticia_idx` (`noticia_id` ASC) ,
  CONSTRAINT `fk_noticia_has_palavra_chave_noticia`
    FOREIGN KEY (`noticia_id`)
    REFERENCES `crud_noticia`.`noticia` (`id_noticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_has_palavra_chave_palavra_chave1`
    FOREIGN KEY (`palavra_chave_id`)
    REFERENCES `crud_noticia`.`palavra_chave` (`id_palavra_chave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
